<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'نظارة شمسية كلاسيك UV400',
                'slug' => 'classic-uv-sunglasses',
                'original_price' => '90.00',
                'price' => '55.00',
                'discount_percentage' => 0,
                'total_discount_percentage' => 0,
                'savings' => '0.00',
                'size' => 'One Size',
                'exterior_image' => 'https://images.unsplash.com/photo-1511499767150-a48a237f0083',
                'interior_images' => [
                    'https://images.unsplash.com/photo-1508296695146-257a814070b4',
                    'https://images.unsplash.com/photo-1577803645773-f96470509666',
                    'https://images.unsplash.com/photo-1517841905240-472988babdf9',
                ],
                'categories' => ['accessories', 'sunglasses'],
                'category' => 'sunglasses',
                'tags' => ['نظارات', 'UV400'],
                'in_stock' => true,
                'featured' => true,
                'description' => 'نظارة شمسية خفيفة بعدسات UV400 لحماية العين.',
                'benefits' => ['حماية من الشمس', 'إطار خفيف'],
                'rating' => 4.7,
                'reviews' => 320,
                'sold_count' => 1200,
            ],
            [
                'name' => 'ساعة يد رجالية كلاسيكية',
                'slug' => 'classic-mens-watch',
                'original_price' => '150.00',
                'price' => '95.00',
                'discount_percentage' => 0,
                'total_discount_percentage' => 0,
                'savings' => '0.00',
                'size' => '42mm',
                'exterior_image' => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30',
                'interior_images' => [
                    'https://images.unsplash.com/photo-1508057198894-247b23fe5ade',
                    'https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b',
                    'https://images.unsplash.com/photo-1518546305927-5a555bb7020d',
                ],
                'categories' => ['accessories'],
                'category' => 'watches',
                'tags' => ['ساعة'],
                'in_stock' => true,
                'featured' => true,
                'description' => 'ساعة يد أنيقة بتصميم كلاسيكي.',
                'benefits' => ['مقاومة للماء'],
                'rating' => 4.6,
                'reviews' => 210,
                'sold_count' => 850,
            ],
            [
                'name' => 'سوار جلد طبيعي',
                'slug' => 'leather-bracelet',
                'original_price' => '60.00',
                'price' => '35.00',
                'discount_percentage' => 0,
                'total_discount_percentage' => 0,
                'savings' => '0.00',
                'size' => 'Adjustable',
                'exterior_image' => 'https://images.unsplash.com/photo-1611085583191-a3b181a88401',
                'interior_images' => [
                    'https://images.unsplash.com/photo-1588444837495-c6cfeb53bfc8',
                    'https://images.unsplash.com/photo-1573408301185-9146fe634ad0',
                    'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f',
                ],
                'categories' => ['accessories'],
                'category' => 'bracelets',
                'tags' => ['جلد'],
                'in_stock' => true,
                'featured' => false,
                'description' => 'سوار جلد طبيعي بتصميم عصري.',
                'benefits' => ['جلد طبيعي'],
                'rating' => 4.5,
                'reviews' => 100,
                'sold_count' => 400,
            ],
            [
                'name' => 'خاتم ستانلس ستيل',
                'slug' => 'stainless-ring',
                'original_price' => '40.00',
                'price' => '22.00',
                'discount_percentage' => 0,
                'total_discount_percentage' => 0,
                'savings' => '0.00',
                'size' => '7-12',
                'exterior_image' => 'https://images.unsplash.com/photo-1605100804763-247f67b3557e',
                'interior_images' => [
                    'https://images.unsplash.com/photo-1589987607627-616cac3cdd20',
                    'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908',
                    'https://images.unsplash.com/photo-1596944924616-7b38e7cfac36',
                ],
                'categories' => ['accessories'],
                'category' => 'rings',
                'tags' => ['خاتم'],
                'in_stock' => true,
                'featured' => false,
                'description' => 'خاتم أنيق مصنوع من الستانلس ستيل.',
                'benefits' => ['مقاوم للصدأ'],
                'rating' => 4.4,
                'reviews' => 70,
                'sold_count' => 300,
            ],
            [
                'name' => 'سلسلة رقبة ذهبية',
                'slug' => 'gold-necklace',
                'original_price' => '85.00',
                'price' => '60.00',
                'discount_percentage' => 0,
                'total_discount_percentage' => 0,
                'savings' => '0.00',
                'size' => '45cm',
                'exterior_image' => 'https://images.unsplash.com/photo-1611599537845-1c7aca0091c0',
                'interior_images' => [
                    'https://images.unsplash.com/photo-1602752250015-52934bc45613',
                    'https://images.unsplash.com/photo-1605100804763-247f67b3557e',
                    'https://images.unsplash.com/photo-1588444837495-c6cfeb53bfc8',
                ],
                'categories' => ['jewelry'],
                'category' => 'necklaces',
                'tags' => ['ذهب'],
                'in_stock' => true,
                'featured' => false,
                'description' => 'سلسلة ذهبية أنيقة مناسبة للمناسبات.',
                'benefits' => ['مضاد للحساسية'],
                'rating' => 4.6,
                'reviews' => 140,
                'sold_count' => 520,
            ],
            [
                'name' => 'نظارة شمسية رياضية',
                'slug' => 'sport-sunglasses',
                'original_price' => '110.00',
                'price' => '70.00',
                'discount_percentage' => 0,
                'total_discount_percentage' => 0,
                'savings' => '0.00',
                'size' => 'One Size',
                'exterior_image' => 'https://images.unsplash.com/photo-1572635196237-14b3f281503f',
                'interior_images' => [
                    'https://images.unsplash.com/photo-1577803645773-f96470509666',
                    'https://images.unsplash.com/photo-1508296695146-257a814070b4',
                    'https://images.unsplash.com/photo-1511499767150-a48a237f0083',
                ],
                'categories' => ['accessories'],
                'category' => 'sunglasses',
                'tags' => ['رياضي'],
                'in_stock' => true,
                'featured' => false,
                'description' => 'نظارة شمسية مخصصة للأنشطة الرياضية.',
                'benefits' => ['عدسات مستقطبة'],
                'rating' => 4.8,
                'reviews' => 200,
                'sold_count' => 900,
            ],
            [
                'name' => 'أوراق لعب فاخرة',
                'slug' => 'premium-playing-cards',
                'original_price' => '35.00',
                'price' => '20.00',
                'discount_percentage' => 0,
                'total_discount_percentage' => 0,
                'savings' => '0.00',
                'size' => 'Standard',
                'exterior_image' => 'https://images.unsplash.com/photo-1606167668584-78701c57f13d',
                'interior_images' => [
                    'https://images.unsplash.com/photo-1596495578065-6e0763fa1178',
                    'https://images.unsplash.com/photo-1595433562696-7b1e11cfc06c',
                    'https://images.unsplash.com/photo-1616627981431-95c0f37db114',
                ],
                'categories' => ['games'],
                'category' => 'cards',
                'tags' => ['ألعاب'],
                'in_stock' => true,
                'featured' => false,
                'description' => 'أوراق لعب بتصميم فاخر.',
                'benefits' => ['جودة عالية'],
                'rating' => 4.5,
                'reviews' => 60,
                'sold_count' => 300,
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(['slug' => $product['slug']], $product);
        }
    }
}
